include: package:very_good_analysis/analysis_options.2.4.0.yaml

analyzer:
  exclude:
    - lib/**/*.gr.dart
    - lib/**/*.config.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - test/**/*.mocks.dart

  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

  errors:
    # Allow having TODOs in the code.
    todo: ignore

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    avoid_print: true  # Uncomment to disable the `avoid_print` rule
    prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
    avoid_equals_and_hash_code_on_mutable_classes: false
    always_use_package_imports: false
    sort_constructors_first: false
    use_late_for_private_fields_and_variables: false
    prefer_const_declarations: false
    unnecessary_overrides: false

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
