name: flutter_strong_boilerplate
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Dependency Injection Pure Dart
  states_rebuilder: ^5.0.0
  firebase_analytics: ^9.0.4
  firebase_crashlytics: ^2.4.4
  bloc_test: ^9.0.2
  flutter_bloc: ^8.0.1
  firebase_core: ^1.10.6
  google_fonts: ^2.2.0
  logger: ^1.0.0
  flutter_svg: ^0.22.0
  cached_network_image: ^3.1.0
  shared_preferences: ^2.0.6
  dio: ^4.0.4
  equatable: ^2.0.3
  mocktail: ^0.2.0
  flutter_spinkit: ^5.1.0
  photo_view: ^0.12.0
  better_player: ^0.0.73
  another_flushbar: ^1.10.24
  url_launcher: ^6.0.17
  intl: ^0.17.0
  share: ^2.0.4
  flutter_local_notifications: ^9.2.0
  image: ^3.1.0
  path_provider: ^2.0.8
  get: ^4.6.1
  injectable: ^1.5.3
  image_picker: ^0.8.5
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  json_serializable: ^6.1.4
  infinite_scroll_pagination: ^3.1.0
  http_parser: ^4.0.0
  go_router: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^2.4.0
  freezed: ^1.1.0
  build_runner: ^2.1.7
  json_annotation: ^4.4.0
  injectable_generator: any
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
