name: flutter_strong_boilerplate
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_analytics: ^9.0.4
  firebase_crashlytics: ^2.4.4
  bloc_test: ^9.0.2
  flutter_bloc: ^8.0.1
  firebase_core: ^1.10.6
  google_fonts: ^2.2.0
  logger: ^1.0.0
  flutter_svg: ^0.22.0
  cached_network_image: ^3.1.0
  shared_preferences: ^2.0.6
  dio: ^4.0.4
  equatable: ^2.0.3
  mockito: ^5.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
