name: test
on:
  pull_request:
    branches:
      - main
      - staging
      - development
  push:
    branches:
      - main
      - staging
      - development

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
          flutter-version: '2.10.3'
      - run: |
          flutter doctor
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter test --coverage
          flutter analyze
          bash <(curl -s https://codecov.io/bash -t ${{ secrets.CODECOV_TOKEN }})